import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { BackgroundBeams } from "@/components/ui/background-beams";
import { ShootingStars } from "@/components/ui/shooting-stars";
import { StarsBackground } from "@/components/ui/stars-background";
import CTASection from "@/sections/CTASection";

/* =======================
   METADATA
======================= */

export const metadata: Metadata = {
  title: "Shahzad Sohail",
  description: "Generated by create next app",
};

/* =======================
   ROOT LAYOUT
======================= */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="
          antialiased
          bg-background
          overflow-x-hidden
          font-sans
        "
      >
        {/* Background Effects */}
        <StarsBackground />
        {/* <BackgroundBeams className="absolute inset-0 z-0 pointer-events-none" /> */}
        <ShootingStars />

        {/* Layout */}
        <Navbar />
        {children}
        <CTASection />
        <Footer />
      </body>
    </html>
  );
}
