import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ShootingStars } from "@/components/ui/shooting-stars";
import { StarsBackground } from "@/components/ui/stars-background";
import CTASection from "@/sections/CTASection";

import { Outfit } from "next/font/google";

/* =======================
   FONT
======================= */

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

/* =======================
   METADATA
======================= */

export const metadata: Metadata = {
  title: "Shahzad Sohail",
  description: "Generated by create next app",
};

/* =======================
   ROOT LAYOUT
======================= */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.variable}>
      <body
        className="
          antialiased
          bg-background
          overflow-x-hidden
        "
      >
        {/* Background Effects */}
        <StarsBackground />
        <ShootingStars />

        {/* Layout */}
        <Navbar />
        {children}
        <CTASection />
        <Footer />
      </body>
    </html>
  );
}
